export { DOMAIN_LIMITS } from './limits.js';
export {
  normalizePlanContent,
  type NormalizedPlanContent,
} from './normalize.js';
export { validatePlanCandidate } from './validation.js';
export {
  DOMAIN_ERROR_CATEGORIES,
  fail,
  succeed,
  type DomainErrorCategory,
  type DomainErrorCode,
  type DomainErrorDetail,
  type DomainFailure,
  type DomainResult,
  type DomainSuccess,
} from './errors.js';
export {
  IDENTIFIER_KINDS,
  IDENTIFIER_PATTERN,
  brandIdentifier,
  type IdentifierForKind,
  type IdentifierKind,
  type IdentityAllocator,
} from './identity.js';
export type {
  AcceptedRevisionRef,
  ActivePlanAggregate,
  BoundedOpaqueText,
  CanonicalPlanContent,
  Context,
  ContextEntry,
  ContextEntryId,
  DeletedPlanAggregate,
  Goal,
  GoalId,
  InternalOwnerId,
  LearnerProgressRecord,
  LongText,
  Milestone,
  MilestoneId,
  NonCompleteProgressState,
  NonEmptyReadonlyArray,
  NonNegativeInteger,
  PlanAggregate,
  PlanDeletionTombstone,
  PlanId,
  PlanItem,
  PlanItemId,
  PlanLifecycle,
  PositiveInteger,
  ProgressState,
  Resource,
  ResourceId,
  RevisionId,
  SafeHttpsUrl,
  ShortText,
  Timestamp,
  Topic,
  TopicId,
} from './types.js';
